#if defined(LANGUAGE_EN_US)
  #define TXT_BACK "Back"
  #define TXT_CLOCK "Clock"
  #define TXT_SETTINGS "Settings"
  #define TXT_NEVER "Never"
  #define TXT_SEC "seconds"
  #define TXT_MIN	"minutes"
  #define TXT_AUTO_DIM "SET AUTO DIM TIME"
  #define TXT_SET_BRIGHT "SET BRIGHTNESS"
  #define TXT_BATT_INFO "Battery Info"
  #define TXT_BRIGHT "Brightness"
  #define TXT_SET_CLOCK "Set Clock"
  #define TXT_ROTATION "Rotation"
  #define TXT_ABOUT "About"
  #define TXT_REBOOT "Reboot"
  #define TXT_CLR_SETTINGS "Clear Settings"
  #define TXT_CLRING_SETTINGS "Restoring Default\nSettings..."
  #define TXT_RIGHT "Right"
  #define TXT_LEFT "Left"
  #define TXT_BATT "Battery: "
  #define TXT_EXIT "Press any key to exit"
  #define TXT_RG_AMERICAS "Region:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Select: Go/Pause"
  #define TXT_SEL_EXIT "Next: Exit"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "Americas / Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Front Key: Go/Pause"
  #define TXT_SET_HOUR "SET HOUR"
  #define TXT_SET_MIN "SET MINUTE"
  #define TXT_ADV "Advertising:\n"  
  #define TXT_SP_RND "Swift Pair Random"
  #define TXT_SEL_EXIT2 "\n\nNext: Exit"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " Combined BT Spam"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfer Number"
  #define TXT_AJ_TV_COLOR "TV Color Balance"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "SourApple Advertisement: "
  #define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
  #define TXT_AJ_ADV "AppleJuice Advertisement: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "Open"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNext: Back\n"
  #define TXT_HOLD_CLONE "Hold Select: Clone\n"
  #define TXT_WF_SCN "WiFi Scan"
  #define TXT_WF_SCNING "Scanning..."
  #define TXT_INST_NXT "Next: Down Arrow"
  #define TXT_INST_PRV "Prev: Up Arrow"
  #define TXT_INST_SEL "Sel : Enter or ->"
  #define TXT_INST_HOME "Home: Esc   or <- "
  #define TXT_INST_PRSS_KEY "         Press a key"
  #define TXT_STK_NXT "Next: Side Button"
  #define TXT_STK_SEL "Sel : M5 Button"
  #define TXT_STK_HOME "Home: Power Button"
  #define TXT_SDCARD "Mount/Unmount SD"
  #define TXT_DEAUTH_START "Select>Start DEAUTH\n"
  #define TXT_DEAUTH_STOP "Select>Stop DEAUTH \n"
  #define TXT_HOLD_ATTACK "Hold Select: Attack\n"
  #define TXT_WFA_PORTAL "Clone Portal"
  #define TXT_WFA_DEAUTH "Deauth attack"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Black"
  #define TXT_NAVY "Navy"
  #define TXT_DARKGREEN "Dark Green"
  #define TXT_DARKCYAN "Dark Cyan"
  #define TXT_MAROON "Maroon"
  #define TXT_PURPLE "Purple"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "Light Grey"
  #define TXT_DARKGREY "Dark Grey"
  #define TXT_BLUE "Blue"
  #define TXT_GREEN "Green"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Red"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Yellow"
  #define TXT_WHITE "White"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "Green Yellow"
  #define TXT_PINK "Pink"
  #define TXT_COLOR "Custom Colors"
  #define TXT_SET_FGCOLOR "MAIN COLOR"
  #define TXT_SET_BGCOLOR "BACKGROUND COLOR"
  #define TXT_THEME "Color Theme"
  #define TXT_hw_to_conect "How to\nconnect:"
  #define TXT_snsor_req "sensor\nrequired" 
  #define TXT_IR_TX "IR Transmit"
  #define TXT_IR_RX "IR Receive"
#endif

#if defined(LANGUAGE_GER)
  #define TXT_BACK "Zurueck"
  #define TXT_CLOCK "Uhr"
  #define TXT_SETTINGS "Einstellungen"
  #define TXT_NEVER "Nie"
  #define TXT_SEC "sekunden"
  #define TXT_MIN	"minuten"
  #define TXT_AUTO_DIM "AUTOMATISCHE DIM ZEIT WAEHLEN"
  #define TXT_SET_BRIGHT "HELLIGKEIT WAEHLEN"
  #define TXT_BATT_INFO "Akku Info"
  #define TXT_BRIGHT "Helligkeit"
  #define TXT_SET_CLOCK "Zeit Einstellen"
  #define TXT_ROTATION "Richtung"
  #define TXT_ABOUT "About"
  #define TXT_REBOOT "Reboot"
  #define TXT_CLR_SETTINGS "EEPROM loeschen"
  #define TXT_CLRING_SETTINGS "Einstellungen\nwerden geloescht..."
  #define TXT_RIGHT "Rechts"
  #define TXT_LEFT "Links"
  #define TXT_BATT "Akku: "
  #define TXT_EXIT "Belibige Taste druecken"
  #define TXT_RG_AMERICAS "Region:\nAmerika / Asien\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Select: Start/Pause"
  #define TXT_SEL_EXIT "Next: Exit"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "Amerika / Asien"
  #define TXT_MN_EMEA "EU/MidEast/Afrika"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Front Key: Start/Pause"
  #define TXT_SET_HOUR "Stunde waehlen"
  #define TXT_SET_MIN "Minuten waehlen"
  #define TXT_ADV "Werbung:\n"  
  #define TXT_SP_RND "Schnelles Paar zufaellig"
  #define TXT_SEL_EXIT2 "\n\nNext: Exit"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " Kombinierter BT Spam"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Uebertragungsnr."
  #define TXT_AJ_TV_COLOR "TV-Farbbalance"
  #define TXT_STP_NW_PH "Telefon einrichten"
  #define TXT_SA_ADV "SourApple Werbung: "
  #define TXT_SP_ADV "SwiftPair Werbung: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Werbung: "
  #define TXT_AJ_ADV "AppleJuice Werbung: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Wifi scannen"
  #define TXT_WF_SPAM_FUN "Spam Lustig"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "oeffnen"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNext: Zurueck\n"
  #define TXT_HOLD_CLONE "Hold Select: Klonen\n"
  #define TXT_WF_SCN "WiFi scannen"
  #define TXT_WF_SCNING "Scanning..."
  #define TXT_INST_NXT "Next: Pfeil nach unten"
  #define TXT_INST_PRV "Prev: Pfeil nach oben"
  #define TXT_INST_SEL "Sel : Enter oder ->"
  #define TXT_INST_HOME "Home: Esc   oder <- "
  #define TXT_INST_PRSS_KEY "   druecke eine Taste"
  #define TXT_STK_NXT "Next: Seitentaste"
  #define TXT_STK_SEL "Sel : M5 Taste"
  #define TXT_STK_HOME "Home: Power Taste"
  #define TXT_SDCARD "Mount/Unmount SD"
  #define TXT_DEAUTH_START "Select>Start DEAUTH\n"
  #define TXT_DEAUTH_STOP "Select>Stop DEAUTH \n"
  #define TXT_HOLD_ATTACK "Hold Select: Attack\n"
  #define TXT_WFA_PORTAL "Clone Portal"
  #define TXT_WFA_DEAUTH "Deauth Attacke"
  #define TXT_WFA_COMBINED "Deauth+Klonen"
  #define TXT_BLACK "Schwarz"
  #define TXT_NAVY "Marine"
  #define TXT_DARKGREEN "Dunkelgruen"
  #define TXT_DARKCYAN "Dunkles Cyan"
  #define TXT_MAROON "Kastanienbraun"
  #define TXT_PURPLE "Lila"
  #define TXT_OLIVE "Olivengruen"
  #define TXT_LIGHTGREY "Hellgrau"
  #define TXT_DARKGREY "Dunkelgrau"
  #define TXT_BLUE "Blau"
  #define TXT_GREEN "Gruen"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Rot"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Gelb"
  #define TXT_WHITE "Weiss"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "Gruen Gelb"
  #define TXT_PINK "Rosa"
  #define TXT_COLOR "Eigene Farben"
  #define TXT_SET_FGCOLOR "HAUPTFARBE"
  #define TXT_SET_BGCOLOR "HINTERGRUNDFARBE"
  #define TXT_THEME "Farbthema"
  #define TXT_hw_to_conect "Die\nverbinungen:"
  #define TXT_snsor_req "sensor\nwird gebrauch" 
  #define TXT_IR_TX "IR Senden"
  #define TXT_IR_RX "IR Empfangen"
#endif

#if defined(LANGUAGE_PT_BR)
  #define TXT_BACK "Voltar"
  #define TXT_CLOCK "Relogio"
  #define TXT_SETTINGS "Configuracoes"
  #define TXT_NEVER "Nunca"
  #define TXT_SEC "segundos"
  #define TXT_MIN	"minutos"
  #define TXT_AUTO_DIM "AJUSTAR LUZ DE FUNDO"
  #define TXT_SET_BRIGHT "BRILHO DA TELA"
  #define TXT_BATT_INFO "Estado da Bateria"
  #define TXT_BRIGHT "Brilho"
  #define TXT_SET_CLOCK "Ajustar Relogio"
  #define TXT_ROTATION "Rotacao"
  #define TXT_ABOUT "Sobre"
  #define TXT_REBOOT "Reiniciar M5"
  #define TXT_CLR_SETTINGS "Resetar Ajustes"
  #define TXT_CLRING_SETTINGS "Aplicando Ajustes\nPadrao..."
  #define TXT_RIGHT "Direita"
  #define TXT_LEFT "Esquerda"
  #define TXT_BATT "Bateria: "
  #define TXT_EXIT "Pressione qualquer tecla para sair"
  #define TXT_RG_AMERICAS "Regiao:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Regiao: EMEA"
  #define TXT_SEL_GO_PAUSE "Ok: Iniciar/Parar"
  #define TXT_SEL_EXIT "Seta 'v' : Sair"
  #define TXT_TRIG_TV "TVBG em funcionamento..."
  #define TXT_MN_AMERICA "Americas/Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Regiao"
  #define TXT_FK_GP "Botao Frontal:Iniciar/Pausar"
  #define TXT_SET_HOUR "AJUSTAR HORA"
  #define TXT_SET_MIN "AJUSTAR MINUTO"
  #define TXT_ADV "Aviso:\n"  
  #define TXT_SP_RND "Swift Pair Aleatorio"
  #define TXT_SEL_EXIT2 "\n\nProx: Sair"
  #define TXT_BT_SPAM "Bluetooth Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM "BT Spam Combinado"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transferir Numero"
  #define TXT_AJ_TV_COLOR "Balanco de Cor TV"
  #define TXT_STP_NW_PH "Novo Aparelho"
  #define TXT_SA_ADV "Aviso SourApple: "
  #define TXT_SP_ADV "Aviso SwiftPair: '%s' - "
  #define TXT_AD_SPAM_ADV "Aviso Android Spam: "
  #define TXT_AJ_ADV "Aviso AppleJuice: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - SSIDs Aleatorios\n"
  #define TXT_WF_SCAN "Escanear Wifi"
  #define TXT_WF_SPAM_FUN "Spam Engracado"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Aleatorio"
  #define TXT_WF_RESCAN "[RESCANEAR]"
  #define TXT_WF_OPEN "Aberto"
  #define TXT_WF_CHANN "Canal: %d\n"
  #define TXT_WF_CRYPT "Cripto: %s\n"
  #define TXT_SEL_BACK "\nProx: Voltar\n"
  #define TXT_HOLD_CLONE "Segurar Ok: Clonar\n"
  #define TXT_WF_SCN "Escanear \n   Wifi"
  #define TXT_WF_SCNING "Escaneando..."
  #define TXT_INST_NXT "Prox: Seta v"
  #define TXT_INST_PRV "Anterior: Seta ^"
  #define TXT_INST_SEL "Sel : Ok ou Seta >"
  #define TXT_INST_HOME "Home: Esc ou Seta <"
  #define TXT_INST_PRSS_KEY "Pressione uma tecla"
  #define TXT_STK_NXT "Prox: Botao do Lado"
  #define TXT_STK_SEL "Sel : Botao M5"
  #define TXT_STK_HOME "Home: Botao Power"
  #define TXT_SDCARD "Monta/Desmonta SD"
  #define TXT_DEAUTH_START "Sel: Iniciar DEAUTH\n"
  #define TXT_DEAUTH_STOP "Sel: Parar DEAUTH  \n"
  #define TXT_HOLD_ATTACK "Segurar Ok: Atacar\n"
  #define TXT_WFA_PORTAL "Clonar Portal"
  #define TXT_WFA_DEAUTH "Ataque Deauth"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Preto"
  #define TXT_NAVY "Azul Escuro"
  #define TXT_DARKGREEN "Verde Escuro"
  #define TXT_DARKCYAN "Ciano Escuro"
  #define TXT_MAROON "Vermelho Escuro"
  #define TXT_PURPLE "Roxo"
  #define TXT_OLIVE "Castanho"
  #define TXT_LIGHTGREY "Cinzo Claro"
  #define TXT_DARKGREY "Cinzo Escuro"
  #define TXT_BLUE "Azul"
  #define TXT_GREEN "Verde"
  #define TXT_CYAN "Ciano"
  #define TXT_RED "Vermelho"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Amarelo"
  #define TXT_WHITE "Branco"
  #define TXT_ORANGE "Alaranjado"
  #define TXT_GREENYELLOW "Verde Amarelo"
  #define TXT_PINK "Rosa"
  #define TXT_COLOR "Mudar Cores"
  #define TXT_SET_FGCOLOR "COR PRINCIPAL"
  #define TXT_SET_BGCOLOR "COR DE FUNDO"
  #define TXT_THEME "Tema De Cores"
  #define TXT_hw_to_conect "como\nconectar:"
  #define TXT_snsor_req "sensor\nnecessrio" 
  #define TXT_IR_TX "IR Transmite"
  #define TXT_IR_RX "IR Receber"
#endif
